-- Migration 37: Add is_test and test_run_id columns to support QA Testing & Audit Center

ALTER TABLE clients ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE service_stages ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE service_catalog ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE service_packs ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE payroll_payments ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE operational_reserve_movements ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE company_settings ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE website_settings ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE website_services ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE website_books ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
ALTER TABLE website_sections ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT FALSE, ADD COLUMN IF NOT EXISTS test_run_id TEXT;
