-- Migration 28: Cotización Rápida Columns
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS prospect_id UUID REFERENCES prospects(id) ON DELETE SET NULL;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS manuscript_pages INTEGER DEFAULT 0;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS extension_adjustment_type TEXT DEFAULT 'percentage'; -- 'percentage' or 'fixed'
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS extension_adjustment_value NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS discount NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS total NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'CLP';
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS includes_iva BOOLEAN DEFAULT FALSE;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'borrador';
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS converted_to_service BOOLEAN DEFAULT FALSE;
ALTER TABLE quotations ADD COLUMN IF NOT EXISTS service_id UUID;

ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS quotation_id UUID REFERENCES quotations(id) ON DELETE CASCADE;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS concept TEXT;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS unit_price NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS total NUMERIC(12,2) DEFAULT 0.00;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS source_type TEXT; -- 'catalog' or 'pack'
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS catalog_id UUID REFERENCES service_catalog(id) ON DELETE SET NULL;
ALTER TABLE quotation_items ADD COLUMN IF NOT EXISTS pack_id UUID REFERENCES service_packs(id) ON DELETE SET NULL;
