export const databaseContract = {
  clients: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    name: 'TEXT',
    email: 'TEXT',
    instagram: 'TEXT',
    phone: 'TEXT',
    country: 'TEXT',
    city: 'TEXT',
    client_type: 'TEXT',
    preferred_currency: 'TEXT',
    status: 'TEXT',
    notes: 'TEXT',
    interest_service: 'TEXT',
    total_agreed_amount: 'NUMERIC(12,2)',
    includes_vat: 'BOOLEAN',
    includes_iva: 'BOOLEAN',
    payment_status: 'TEXT',
    amount_paid: 'NUMERIC(12,2)',
    balance_due: 'NUMERIC(12,2)',
    payment_method: 'TEXT',
    paid_at: 'DATE',
    payment_link_sent: 'BOOLEAN',
    payment_link_sent_at: 'DATE',
    contract_sent: 'BOOLEAN',
    contract_sent_at: 'DATE',
    contract_signed_received: 'BOOLEAN',
    contract_signed_received_at: 'DATE',
    files_received: 'BOOLEAN',
    files_received_at: 'DATE',
    ready_to_start: 'BOOLEAN',
    agreement_notes: 'TEXT',
    currency: 'TEXT',
    selected_services: 'JSONB',
    service_category: 'TEXT',
    agreement_period_type: 'TEXT',
    materials_received: 'BOOLEAN',
    materials_received_at: 'DATE',
    partial_payment_authorized: 'BOOLEAN',
    ready_to_start_reason: 'TEXT',
    services_summary: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  prospects: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    name: 'TEXT',
    email: 'TEXT',
    instagram: 'TEXT',
    phone: 'TEXT',
    contact: 'TEXT',
    origin: 'TEXT',
    interest_service: 'TEXT',
    probability: 'TEXT',
    next_action: 'TEXT',
    followup_date: 'DATE',
    notes: 'TEXT',
    country: 'TEXT',
    city: 'TEXT',
    client_type: 'TEXT',
    preferred_currency: 'TEXT',
    converted_to_client_id: 'UUID',
    converted_client_id: 'UUID',
    converted_to_client: 'BOOLEAN',
    converted_at: 'TIMESTAMP WITH TIME ZONE',
    total_agreed_amount: 'NUMERIC(12,2)',
    agreed_amount: 'NUMERIC(12,2)',
    amount: 'NUMERIC(12,2)',
    includes_vat: 'BOOLEAN',
    includes_iva: 'BOOLEAN',
    payment_status: 'TEXT',
    amount_paid: 'NUMERIC(12,2)',
    balance_due: 'NUMERIC(12,2)',
    payment_method: 'TEXT',
    paid_at: 'DATE',
    payment_date: 'DATE',
    payment_link_sent: 'BOOLEAN',
    payment_link_sent_at: 'DATE',
    contract_sent: 'BOOLEAN',
    contract_sent_at: 'DATE',
    contract_signed_received: 'BOOLEAN',
    contract_signed_received_at: 'DATE',
    files_received: 'BOOLEAN',
    files_received_at: 'DATE',
    ready_to_start: 'BOOLEAN',
    agreement_notes: 'TEXT',
    currency: 'TEXT',
    selected_services: 'JSONB',
    service_category: 'TEXT',
    agreement_period_type: 'TEXT',
    agreement_start_date: 'DATE',
    agreement_duration_value: 'TEXT',
    agreement_duration_unit: 'TEXT',
    agreement_end_date: 'DATE',
    materials_received: 'BOOLEAN',
    materials_received_at: 'DATE',
    partial_payment_authorized: 'BOOLEAN',
    ready_to_start_reason: 'TEXT',
    services_summary: 'TEXT',
    status: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  quotations: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    client_id: 'UUID',
    prospect_id: 'UUID',
    author_name: 'TEXT',
    author_email: 'TEXT',
    author_phone: 'TEXT',
    author_instagram: 'TEXT',
    origin: 'TEXT',
    country: 'TEXT',
    city: 'TEXT',
    object: 'TEXT',
    quote_number: 'TEXT',
    issue_date: 'DATE',
    valid_until: 'DATE',
    validity_days: 'INTEGER',
    manuscript_pages: 'INTEGER',
    extension_adjustment_type: 'TEXT',
    extension_adjustment_value: 'NUMERIC(12,2)',
    subtotal: 'NUMERIC(12,2)',
    discount: 'NUMERIC(12,2)',
    tax_amount: 'NUMERIC(12,2)',
    total: 'NUMERIC(12,2)',
    currency: 'TEXT',
    includes_iva: 'BOOLEAN',
    includes_vat: 'BOOLEAN',
    iva_mode: 'TEXT',
    tax_rate: 'NUMERIC(5,2)',
    net_amount: 'NUMERIC(12,2)',
    payment_plan_type: 'TEXT',
    upfront_percentage: 'NUMERIC(5,2)',
    installments: 'INTEGER',
    included_items: 'JSONB',
    excluded_items: 'JSONB',
    start_condition_items: 'JSONB',
    proposal_format: 'TEXT',
    show_signatures: 'BOOLEAN',
    has_alternatives: 'BOOLEAN',
    payment_terms: 'TEXT',
    work_timeline: 'TEXT',
    includes_notes: 'TEXT',
    excludes_notes: 'TEXT',
    start_conditions: 'TEXT',
    legal_notes: 'TEXT',
    other_notes: 'TEXT',
    status: 'TEXT',
    pdf_url: 'TEXT',
    sent_at: 'TIMESTAMP WITH TIME ZONE',
    accepted_at: 'TIMESTAMP WITH TIME ZONE',
    rejected_at: 'TIMESTAMP WITH TIME ZONE',
    converted_to_prospect: 'BOOLEAN',
    converted_prospect_id: 'UUID',
    converted_to_client: 'BOOLEAN',
    converted_client_id: 'UUID',
    converted_at: 'TIMESTAMP WITH TIME ZONE',
    converted_to_service: 'BOOLEAN',
    service_id: 'UUID',
    notes: 'TEXT',
    exchange_rate: 'NUMERIC(12,4)',
    value_converted: 'NUMERIC(12,2)',
    rate_date: 'DATE',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    updated_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  quotation_items: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    quotation_id: 'UUID',
    catalog_id: 'UUID',
    pack_id: 'UUID',
    concept: 'TEXT',
    description: 'TEXT',
    unit_price: 'NUMERIC(12,2)',
    quantity: 'INTEGER',
    total: 'NUMERIC(12,2)',
    source_type: 'TEXT',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  services: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    client_id: 'UUID',
    type: 'TEXT',
    service_type: 'TEXT',
    title: 'TEXT',
    book_title: 'TEXT',
    status: 'TEXT',
    value: 'NUMERIC(12,2)',
    total_agreed_amount: 'NUMERIC(12,2)',
    currency: 'TEXT',
    start_date: 'DATE',
    estimated_delivery: 'DATE',
    estimated_delivery_date: 'DATE',
    notes: 'TEXT',
    stage: 'TEXT',
    current_stage: 'TEXT',
    advance_percent: 'INTEGER',
    exchange_rate: 'NUMERIC(12,4)',
    value_converted: 'NUMERIC(12,2)',
    rate_date: 'DATE',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  service_stages: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    service_id: 'UUID',
    stage_name: 'TEXT',
    name: 'TEXT',
    description: 'TEXT',
    order_index: 'INTEGER',
    status: 'TEXT',
    start_date: 'DATE',
    end_date: 'DATE',
    started_at: 'DATE',
    completed_at: 'DATE',
    responsible: 'TEXT',
    notes: 'TEXT',
    active: 'BOOLEAN',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  documents: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    client_id: 'UUID',
    name: 'TEXT',
    file_name: 'TEXT',
    file_url: 'TEXT',
    file_path: 'TEXT',
    category: 'TEXT',
    uploaded_by: 'TEXT',
    uploaded_at: 'TIMESTAMP WITH TIME ZONE',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  incomes: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    client_id: 'UUID',
    service_id: 'UUID',
    amount: 'NUMERIC(12,2)',
    concept: 'TEXT',
    category: 'TEXT',
    payment_method: 'TEXT',
    payment_date: 'DATE',
    notes: 'TEXT',
    source_type: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  expenses: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    amount: 'NUMERIC(12,2)',
    concept: 'TEXT',
    category: 'TEXT',
    payment_method: 'TEXT',
    payment_date: 'DATE',
    notes: 'TEXT',
    client_id: 'UUID',
    service_id: 'UUID',
    fund_type: 'TEXT',
    money_source: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  staff: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    name: 'TEXT',
    email: 'TEXT',
    phone: 'TEXT',
    role: 'TEXT',
    status: 'TEXT',
    salary: 'NUMERIC(12,2)',
    payment_period: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  payroll_payments: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    staff_id: 'UUID',
    amount: 'NUMERIC(12,2)',
    payment_date: 'DATE',
    status: 'TEXT',
    notes: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  operational_reserve_movements: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    amount: 'NUMERIC(12,2)',
    concept: 'TEXT',
    movement_type: 'TEXT',
    movement_date: 'DATE',
    notes: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  service_catalog: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    name: 'TEXT',
    description: 'TEXT',
    base_price: 'NUMERIC(12,2)',
    currency: 'TEXT',
    includes_vat: 'BOOLEAN',
    includes_iva: 'BOOLEAN',
    category: 'TEXT',
    active: 'BOOLEAN',
    requires_manuscript: 'BOOLEAN',
    requires_materials: 'BOOLEAN',
    requires_signed_contract: 'BOOLEAN',
    requires_agreement_sent: 'BOOLEAN',
    requires_duration: 'BOOLEAN',
    includes_text: 'TEXT',
    excludes_text: 'TEXT',
    default_work_timeline: 'TEXT',
    default_payment_terms: 'TEXT',
    default_start_conditions: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  service_packs: {
    id: 'UUID',
    user_id: 'UUID',
    organization_id: 'UUID',
    name: 'TEXT',
    description: 'TEXT',
    price_special: 'NUMERIC(12,2)',
    currency: 'TEXT',
    includes_vat: 'BOOLEAN',
    includes_iva: 'BOOLEAN',
    active: 'BOOLEAN',
    category: 'TEXT',
    requires_manuscript: 'BOOLEAN',
    requires_materials: 'BOOLEAN',
    requires_signed_contract: 'BOOLEAN',
    requires_agreement_sent: 'BOOLEAN',
    requires_duration: 'BOOLEAN',
    includes_text: 'TEXT',
    excludes_text: 'TEXT',
    default_work_timeline: 'TEXT',
    default_payment_terms: 'TEXT',
    default_start_conditions: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  company_settings: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    company_name: 'TEXT',
    commercial_name: 'TEXT',
    representative_name: 'TEXT',
    representative_role: 'TEXT',
    official_email: 'TEXT',
    phone: 'TEXT',
    website_url: 'TEXT',
    instagram_url: 'TEXT',
    address: 'TEXT',
    city: 'TEXT',
    country: 'TEXT',
    tax_id: 'TEXT',
    logo_url: 'TEXT',
    favicon_url: 'TEXT',
    signature_name: 'TEXT',
    default_legal_text: 'TEXT',
    default_footer_text: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    updated_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  website_settings: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    site_name: 'TEXT',
    public_url: 'TEXT',
    short_description: 'TEXT',
    contact_email: 'TEXT',
    instagram_url: 'TEXT',
    hero_title: 'TEXT',
    hero_subtitle: 'TEXT',
    logo_url: 'TEXT',
    favicon_url: 'TEXT',
    active: 'BOOLEAN',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    updated_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  website_services: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    title: 'TEXT',
    short_description: 'TEXT',
    full_description: 'TEXT',
    price_from: 'NUMERIC(15,2)',
    currency: 'VARCHAR(10)',
    category: 'VARCHAR(50)',
    featured: 'BOOLEAN',
    active: 'BOOLEAN',
    display_order: 'INTEGER',
    visible_on_website: 'BOOLEAN',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  website_books: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    title: 'TEXT',
    author: 'TEXT',
    cover_url: 'TEXT',
    short_description: 'TEXT',
    genre: 'VARCHAR(100)',
    status: 'VARCHAR(50)',
    featured: 'BOOLEAN',
    sale_url: 'TEXT',
    sale_platform: 'VARCHAR(50)',
    active: 'BOOLEAN',
    display_order: 'INTEGER',
    visible_on_website: 'BOOLEAN',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  website_links: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    label: 'TEXT',
    url: 'TEXT',
    link_type: 'VARCHAR(50)',
    related_type: 'VARCHAR(50)',
    related_id: 'VARCHAR(100)',
    active: 'BOOLEAN',
    display_order: 'INTEGER',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  website_sections: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    section_key: 'VARCHAR(50)',
    title: 'TEXT',
    subtitle: 'TEXT',
    content: 'TEXT',
    image_url: 'TEXT',
    active: 'BOOLEAN',
    display_order: 'INTEGER',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  organization_members: {
    id: 'UUID',
    organization_id: 'UUID',
    user_id: 'UUID',
    role: 'TEXT',
    active: 'BOOLEAN',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    email: 'TEXT',
    full_name: 'TEXT',
    area: 'TEXT',
    permissions: 'JSONB'
  },
  income_distributions: {
    id: 'UUID',
    organization_id: 'UUID',
    income_id: 'UUID',
    client_id: 'UUID',
    prospect_id: 'UUID',
    service_id: 'UUID',
    distribution_type: 'TEXT',
    category: 'TEXT',
    amount: 'NUMERIC(12,2)',
    percentage: 'NUMERIC(5,2)',
    status: 'TEXT',
    notes: 'TEXT',
    created_by: 'UUID',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    updated_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  client_funds: {
    id: 'UUID',
    organization_id: 'UUID',
    client_id: 'UUID',
    service_id: 'UUID',
    fund_type: 'TEXT',
    fund_name: 'TEXT',
    initial_amount: 'NUMERIC(12,2)',
    allocated_amount: 'NUMERIC(12,2)',
    used_amount: 'NUMERIC(12,2)',
    balance: 'NUMERIC(12,2)',
    status: 'TEXT',
    notes: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    updated_at: 'TIMESTAMP WITH TIME ZONE',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  fund_movements: {
    id: 'UUID',
    organization_id: 'UUID',
    fund_id: 'UUID',
    income_id: 'UUID',
    expense_id: 'UUID',
    movement_type: 'TEXT',
    amount: 'NUMERIC(12,2)',
    concept: 'TEXT',
    notes: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    created_by: 'UUID',
    is_test: 'BOOLEAN',
    test_run_id: 'TEXT'
  },
  income_tax_reservations: {
    id: 'UUID',
    organization_id: 'UUID',
    income_id: 'UUID',
    tax_type: 'TEXT',
    tax_rate: 'NUMERIC(5,2)',
    taxable_amount: 'NUMERIC(12,2)',
    tax_amount: 'NUMERIC(12,2)',
    status: 'TEXT',
    paid_at: 'DATE',
    notes: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE',
    updated_at: 'TIMESTAMP WITH TIME ZONE'
  },
  crm_error_logs: {
    id: 'UUID',
    error_message: 'TEXT',
    error_stack: 'TEXT',
    module: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE'
  },
  organizations: {
    id: 'UUID',
    name: 'TEXT',
    created_at: 'TIMESTAMP WITH TIME ZONE'
  }
};
